// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeAppCore.Entity.Employee_Details.Entity
{
    public partial class Employee_Details
    {
        [Key]
        public int Worker_Id { get; set; }
        public int User_Id { get; set; }
        [Required]
        [StringLength(15)]
        public string First_Name { get; set; }
        [Required]
        [StringLength(15)]
        public string Second_Name { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date_Of_Joining { get; set; }
        public int Age { get; set; }
        public int Experience { get; set; }
        public int Contact_Number { get; set; }
        [Required]
        [StringLength(100)]
        public string Adress { get; set; }
        public int Location_Id { get; set; }
        public bool Enable_Edit_Button { get; set; }
        public bool Is_Deleted { get; set; }
        /// <summary>
        /// (getdate())
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        /// <summary>
        /// (getdate())
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }

        [ForeignKey(nameof(User_Id))]
        [InverseProperty(nameof(Employee_LogIn.Employee_Details))]
        public virtual Employee_LogIn User_ { get; set; }
    }
}