// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeAppCore.Entity.Employee_Details.Entity
{
    public partial class Employee_LogIn
    {
      

        [Key]
        public int User_Id { get; set; }
        [Required]
        [StringLength(20)]
        public string Username { get; set; }
        [Required]
        [StringLength(15)]
        public string Password { get; set; }
        public bool Is_Admin_User { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_stamp { get; set; }

        [InverseProperty("User_")]
        public virtual ICollection<Employee_Details> Employee_Details { get; set; }
    }
}